import { error } from '@sveltejs/kit';

import { PUBLIC_PRODUCTION_URL } from '$env/static/public';
import { isOriginalHostname } from '$lib/app-routing.js';

// The client module is generated by the `build-client-module` step (see
// package.json) into static/client-module.js and inlined here at build time.
// Serving the bundled string directly avoids a runtime self-fetch of the app's
// own public URL — under adapter-node with ORIGIN set that round-tripped out
// through the edge and failed (TypeError: fetch failed / 500).
import clientModule from '../../../../../static/client-module.js?raw';

export async function GET({ url }) {
	const hostname = url.hostname;

	if (!hostname) {
		throw error(404, 'Host not found.');
	}

	if (!isOriginalHostname(hostname)) {
		throw error(
			405,
			`Not allowed. Only requests to original host (${PUBLIC_PRODUCTION_URL}) are allowed.`
		);
	}

	return new Response(clientModule, {
		headers: {
			'Content-Type': 'application/javascript',
			'Access-Control-Allow-Origin': '*', // Or a specific origin
			'Access-Control-Allow-Methods': 'GET, OPTIONS',
			'Access-Control-Allow-Headers': 'Content-Type'
		}
	});
}
